theme: jekyll-theme-leap-day
title: Documentation
description: Specification of interaction protocol between the Alif Bank system and Partners

#markdown_extensions:
#  - pymdownx.tabbed

#markdown_extensions:
#  - pymdownx.superfences
#  - pymdownx.tabbed:
#      alternate_style: true

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true

